services:
  server:
    build:
      context: .
      target: base
    environment:
      NODE_ENV: development
      REACT_APP_STORE_API_URL: http://fakestoreapi.com
    command: npm start
    ports:
      - 3000:3000
