name: build-n-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t jekku123/redux-online-store --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_STORE_API_URL='http://fakestoreapi.com' .
      - name: Publish image to docker hub
        run: docker push jekku123/redux-online-store:latest
#   deploy:
#     needs: build
#     runs-on: self-hosted
#     steps:
#       - name: Pull image from docker hub
#         run: docker pull jekku123/mern-test-react:latest
#       - name: Delete Old Container
#         run: docker rm -f mern-test-react-container
#       - name: Run docker container
#         run: docker run -d -p 5173:80 --name mern-test-react-container jekku123/mern-test-react

